import { Playlist, Video } from "./@types";

export const playlists: Playlist[] = [
  {
    id: "PLM0lb7jyj5LUKjY5F5mG4XjyvqQ0wqZ3y",
    title: "ReactJS",
    description:
      "ReactJS is a JavaScript library for building user interfaces.",
    thumbnail: "https://i.ytimg.com/vi/4UZrsTqkcW4/maxresdefault.jpg",
    link: "https://www.youtube.com/playlist?list=PLM0lb7jyj5LUKjY5F5mG4XjyvqQ0wqZ3y",
    videos: [
      {
        title: "video 0",
        thumbnail: "https://i.ytimg.com/vi/kGtEax1WQFg/default.jpg",
        link: "https://www.youtube.com/watch?v=kGtEax1WQFg",
        status: "toWatch",
      },
      {
        title: "video 1",
        thumbnail: "https://i.ytimg.com/vi/XV5LwKuk3zc/default.jpg",
        link: "https://www.youtube.com/watch?v=XV5LwKuk3zc",
        status: "toWatch",
      },
      {
        title: "video 2",
        thumbnail: "https://i.ytimg.com/vi/8l691BQ-RGc/default.jpg",
        link: "https://www.youtube.com/watch?v=8l691BQ-RGc",
        status: "toWatch",
      },
      {
        title: "video 3",
        thumbnail: "https://i.ytimg.com/vi/TXWYrnl6dZI/default.jpg",
        link: "https://www.youtube.com/watch?v=TXWYrnl6dZI",
        status: "toWatch",
      },
      {
        title: "video 4",
        thumbnail: "https://i.ytimg.com/vi/PjmAVh4Syvk/default.jpg",
        link: "https://www.youtube.com/watch?v=PjmAVh4Syvk",
        status: "toWatch",
      },
      {
        title: "video 5",
        thumbnail: "https://i.ytimg.com/vi/CZrJpEn6b4I/default.jpg",
        link: "https://www.youtube.com/watch?v=CZrJpEn6b4I",
        status: "toWatch",
      },
      {
        title: "video 6",
        thumbnail: "https://i.ytimg.com/vi/9yhlhKX7ZYM/default.jpg",
        link: "https://www.youtube.com/watch?v=9yhlhKX7ZYM",
        status: "toWatch",
      },
      {
        title: "video 7",
        thumbnail: "https://i.ytimg.com/vi/6BlFPa_MGNg/default.jpg",
        link: "https://www.youtube.com/watch?v=6BlFPa_MGNg",
        status: "toWatch",
      },
      {
        title: "video 8",
        thumbnail: "https://i.ytimg.com/vi/XfREwe2sUGs/default.jpg",
        link: "https://www.youtube.com/watch?v=XfREwe2sUGs",
        status: "toWatch",
      },
      {
        title: "video 9",
        thumbnail: "https://i.ytimg.com/vi/pbvC119ZRDw/default.jpg",
        link: "https://www.youtube.com/watch?v=pbvC119ZRDw",
        status: "toWatch",
      },
    ],
  },
  {
    id: "PLM0lb7jyj5LX5Z4JdQqOgGm5zqJlZU5m8",
    title: "React Native",
    description:
      "React Native is a JavaScript framework for writing real, natively rendering mobile applications for iOS and Android.",
    thumbnail: "https://i.ytimg.com/vi/kGtEax1WQFg/maxresdefault.jpg",
    link: "https://www.youtube.com/playlist?list=PLM0lb7jyj5LX5Z4JdQqOgGm5zqJlZU5m8",
    videos: [
      {
        title: "video 10",
        thumbnail: "https://i.ytimg.com/vi/hg_cpUnBkBc/default.jpg",
        link: "https://www.youtube.com/watch?v=hg_cpUnBkBc",
        status: "toWatch",
      },
      {
        title: "video 11",
        thumbnail: "https://i.ytimg.com/vi/MJ7P1JUyuFA/default.jpg",
        link: "https://www.youtube.com/watch?v=MJ7P1JUyuFA",
        status: "toWatch",
      },
      {
        title: "video 12",
        thumbnail: "https://i.ytimg.com/vi/cdP210MwnLw/default.jpg",
        link: "https://www.youtube.com/watch?v=cdP210MwnLw",
        status: "toWatch",
      },
      {
        title: "video 13",
        thumbnail: "https://i.ytimg.com/vi/txSxteRjpYw/default.jpg",
        link: "https://www.youtube.com/watch?v=txSxteRjpYw",
        status: "toWatch",
      },
      {
        title: "video 14",
        thumbnail: "https://i.ytimg.com/vi/RpBOw56rp1I/default.jpg",
        link: "https://www.youtube.com/watch?v=RpBOw56rp1I",
        status: "toWatch",
      },
      {
        title: "video 15",
        thumbnail: "https://i.ytimg.com/vi/eL5qYJ7y68k/default.jpg",
        link: "https://www.youtube.com/watch?v=eL5qYJ7y68k",
        status: "toWatch",
      },
      {
        title: "video 16",
        thumbnail: "https://i.ytimg.com/vi/QpTPQmBsOyI/default.jpg",
        link: "https://www.youtube.com/watch?v=QpTPQmBsOyI",
        status: "toWatch",
      },
      {
        title: "video 17",
        thumbnail: "https://i.ytimg.com/vi/UJLphDsGzCQ/default.jpg",
        link: "https://www.youtube.com/watch?v=UJLphDsGzCQ",
        status: "toWatch",
      },
      {
        title: "video 18",
        thumbnail: "https://i.ytimg.com/vi/VxLl6XmS__E/default.jpg",
        link: "https://www.youtube.com/watch?v=VxLl6XmS__E",
        status: "toWatch",
      },
      {
        title: "video 19",
        thumbnail: "https://i.ytimg.com/vi/inriP3Vj2wo/default.jpg",
        link: "https://www.youtube.com/watch?v=inriP3Vj2wo",
        status: "toWatch",
      },
      {
        title: "video 20",
        thumbnail: "https://i.ytimg.com/vi/86EO42D6s7E/default.jpg",
        link: "https://www.youtube.com/watch?v=86EO42D6s7E",
        status: "toWatch",
      },
      {
        title: "video 21",
        thumbnail: "https://i.ytimg.com/vi/ORSHG3dfUrk/default.jpg",
        link: "https://www.youtube.com/watch?v=ORSHG3dfUrk",
        status: "toWatch",
      },
      {
        title: "video 22",
        thumbnail: "https://i.ytimg.com/vi/dGkA5u7f1YM/default.jpg",
        link: "https://www.youtube.com/watch?v=dGkA5u7f1YM",
        status: "toWatch",
      },
      {
        title: "video 23",
        thumbnail: "https://i.ytimg.com/vi/Ffia32q_umY/default.jpg",
        link: "https://www.youtube.com/watch?v=Ffia32q_umY",
        status: "toWatch",
      },
      {
        title: "video 24",
        thumbnail: "https://i.ytimg.com/vi/molTIg-zvGI/default.jpg",
        link: "https://www.youtube.com/watch?v=molTIg-zvGI",
        status: "toWatch",
      },
      {
        title: "video 25",
        thumbnail: "https://i.ytimg.com/vi/BayDYRigP5I/default.jpg",
        link: "https://www.youtube.com/watch?v=BayDYRigP5I",
        status: "toWatch",
      },
    ],
  },
  {
    id: "PLM0lb7jyj5LXyf1Y6kxjF5Vb9V9f2Qxgj",
    title: "NodeJS",
    description:
      "Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.",
    thumbnail: "https://i.ytimg.com/vi/zb3Qk8SG5Ms/maxresdefault.jpg",
    link: "https://www.youtube.com/playlist?list=PLM0lb7jyj5LXyf1Y6kxjF5Vb9V9f2Qxgj",
    videos: [
      {
        title: "video 26",
        thumbnail: "https://i.ytimg.com/vi/mJomfTfOJUQ/default.jpg",
        link: "https://www.youtube.com/watch?v=mJomfTfOJUQ",
        status: "toWatch",
      },
      {
        title: "video 27",
        thumbnail: "https://i.ytimg.com/vi/9ZkiY373CHk/default.jpg",
        link: "https://www.youtube.com/watch?v=9ZkiY373CHk",
        status: "toWatch",
      },
      {
        title: "video 28",
        thumbnail: "https://i.ytimg.com/vi/zI69kpGoFRI/default.jpg",
        link: "https://www.youtube.com/watch?v=zI69kpGoFRI",
        status: "toWatch",
      },
      {
        title: "video 29",
        thumbnail: "https://i.ytimg.com/vi/NM2-naJ2zDU/default.jpg",
        link: "https://www.youtube.com/watch?v=NM2-naJ2zDU",
        status: "toWatch",
      },
      {
        title: "video 30",
        thumbnail: "https://i.ytimg.com/vi/bIJASPiSKS4/default.jpg",
        link: "https://www.youtube.com/watch?v=bIJASPiSKS4",
        status: "toWatch",
      },
      {
        title: "video 31",
        thumbnail: "https://i.ytimg.com/vi/5Qlep9sKuX4/default.jpg",
        link: "https://www.youtube.com/watch?v=5Qlep9sKuX4",
        status: "toWatch",
      },
      {
        title: "video 32",
        thumbnail: "https://i.ytimg.com/vi/c9UNoNqwKTQ/default.jpg",
        link: "https://www.youtube.com/watch?v=c9UNoNqwKTQ",
        status: "toWatch",
      },
      {
        title: "video 33",
        thumbnail: "https://i.ytimg.com/vi/rm4x_SwgA28/default.jpg",
        link: "https://www.youtube.com/watch?v=rm4x_SwgA28",
        status: "toWatch",
      },
      {
        title: "video 34",
        thumbnail: "https://i.ytimg.com/vi/a0PRdbFBgY8/default.jpg",
        link: "https://www.youtube.com/watch?v=a0PRdbFBgY8",
        status: "toWatch",
      },
      {
        title: "video 35",
        thumbnail: "https://i.ytimg.com/vi/ZpXB6DkScac/default.jpg",
        link: "https://www.youtube.com/watch?v=ZpXB6DkScac",
        status: "toWatch",
      },
      {
        title: "video 36",
        thumbnail: "https://i.ytimg.com/vi/ShIND2eR1Z0/default.jpg",
        link: "https://www.youtube.com/watch?v=ShIND2eR1Z0",
        status: "toWatch",
      },
      {
        title: "video 37",
        thumbnail: "https://i.ytimg.com/vi/41HzsprDVBE/default.jpg",
        link: "https://www.youtube.com/watch?v=41HzsprDVBE",
        status: "toWatch",
      },
      {
        title: "video 38",
        thumbnail: "https://i.ytimg.com/vi/8UwoThBYvM4/default.jpg",
        link: "https://www.youtube.com/watch?v=8UwoThBYvM4",
        status: "toWatch",
      },
      {
        title: "video 39",
        thumbnail: "https://i.ytimg.com/vi/yqMKsKzUanU/default.jpg",
        link: "https://www.youtube.com/watch?v=yqMKsKzUanU",
        status: "toWatch",
      },
      {
        title: "video 40",
        thumbnail: "https://i.ytimg.com/vi/eCkPGsqn4xw/default.jpg",
        link: "https://www.youtube.com/watch?v=eCkPGsqn4xw",
        status: "toWatch",
      },
      {
        title: "video 41",
        thumbnail: "https://i.ytimg.com/vi/TaY3-eBuf7U/default.jpg",
        link: "https://www.youtube.com/watch?v=TaY3-eBuf7U",
        status: "toWatch",
      },
      {
        title: "video 42",
        thumbnail: "https://i.ytimg.com/vi/pt4ekPqX9Bo/default.jpg",
        link: "https://www.youtube.com/watch?v=pt4ekPqX9Bo",
        status: "toWatch",
      },
      {
        title: "video 43",
        thumbnail: "https://i.ytimg.com/vi/Jy0hMhllf90/default.jpg",
        link: "https://www.youtube.com/watch?v=Jy0hMhllf90",
        status: "toWatch",
      },
      {
        title: "video 44",
        thumbnail: "https://i.ytimg.com/vi/lpCwIPFGMkQ/default.jpg",
        link: "https://www.youtube.com/watch?v=lpCwIPFGMkQ",
        status: "toWatch",
      },
      {
        title: "video 45",
        thumbnail: "https://i.ytimg.com/vi/2at5ac3Po9g/default.jpg",
        link: "https://www.youtube.com/watch?v=2at5ac3Po9g",
        status: "toWatch",
      },
      {
        title: "video 46",
        thumbnail: "https://i.ytimg.com/vi/c_7ukxJz1wE/default.jpg",
        link: "https://www.youtube.com/watch?v=c_7ukxJz1wE",
        status: "toWatch",
      },
      {
        title: "video 47",
        thumbnail: "https://i.ytimg.com/vi/KMJE_0ybg9E/default.jpg",
        link: "https://www.youtube.com/watch?v=KMJE_0ybg9E",
        status: "toWatch",
      },
      {
        title: "video 48",
        thumbnail: "https://i.ytimg.com/vi/dAsxCAQogwA/default.jpg",
        link: "https://www.youtube.com/watch?v=dAsxCAQogwA",
        status: "toWatch",
      },
      {
        title: "video 49",
        thumbnail: "https://i.ytimg.com/vi/hgca3tkyVlY/default.jpg",
        link: "https://www.youtube.com/watch?v=hgca3tkyVlY",
        status: "toWatch",
      },
      {
        title: "video 50",
        thumbnail: "https://i.ytimg.com/vi/Q5lqT7bHoV0/default.jpg",
        link: "https://www.youtube.com/watch?v=Q5lqT7bHoV0",
        status: "toWatch",
      },
      {
        title: "video 51",
        thumbnail: "https://i.ytimg.com/vi/6qSHnTXeUxI/default.jpg",
        link: "https://www.youtube.com/watch?v=6qSHnTXeUxI",
        status: "toWatch",
      },
      {
        title: "video 52",
        thumbnail: "https://i.ytimg.com/vi/9BfMfDJpbjI/default.jpg",
        link: "https://www.youtube.com/watch?v=9BfMfDJpbjI",
        status: "toWatch",
      },
      {
        title: "video 53",
        thumbnail: "https://i.ytimg.com/vi/VfftvZ0J-Ro/default.jpg",
        link: "https://www.youtube.com/watch?v=VfftvZ0J-Ro",
        status: "toWatch",
      },
      {
        title: "video 54",
        thumbnail: "https://i.ytimg.com/vi/VeSUgWHbphk/default.jpg",
        link: "https://www.youtube.com/watch?v=VeSUgWHbphk",
        status: "toWatch",
      },
      {
        title: "video 55",
        thumbnail: "https://i.ytimg.com/vi/zlojM-Jbux4/default.jpg",
        link: "https://www.youtube.com/watch?v=zlojM-Jbux4",
        status: "toWatch",
      },
      {
        title: "video 56",
        thumbnail: "https://i.ytimg.com/vi/rWv0zzEYB2w/default.jpg",
        link: "https://www.youtube.com/watch?v=rWv0zzEYB2w",
        status: "toWatch",
      },
      {
        title: "video 57",
        thumbnail: "https://i.ytimg.com/vi/fw8J9-KhGdU/default.jpg",
        link: "https://www.youtube.com/watch?v=fw8J9-KhGdU",
        status: "toWatch",
      },
    ],
  },
];

export const videos: Video[] = [];
